"""Initial Commit

Revision ID: 2b1a94ac1009
Revises:
Create Date: 2024-07-23 21:02:38.667410

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b1a94ac1009"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usermodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("discord_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ucf_id", sa.Integer(), nullable=True),
        sa.Column("nid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ops_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("infra_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("minecraft", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("surname", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_returning", sa.Boolean(), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("major", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("class_standing", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("shirt_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("did_get_shirt", sa.Boolean(), nullable=True),
        sa.Column(
            "time_availability", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("phone_number", sa.Integer(), nullable=True),
        sa.Column("sudo", sa.Boolean(), nullable=True),
        sa.Column("did_pay_dues", sa.Boolean(), nullable=True),
        sa.Column("join_date", sa.Integer(), nullable=True),
        sa.Column("is_full_member", sa.Boolean(), nullable=True),
        sa.Column("can_vote", sa.Boolean(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column("curiosity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("c3_interest", sa.Boolean(), nullable=True),
        sa.Column("attending", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comments", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
        sa.UniqueConstraint("nid"),
        sa.UniqueConstraint("ucf_id"),
    )
    op.create_table(
        "discordmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mfa", sa.Boolean(), nullable=True),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("banner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("color", sa.Integer(), nullable=True),
        sa.Column("nitro", sa.Integer(), nullable=True),
        sa.Column("locale", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usermodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ethicsformmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hack_others", sa.Boolean(), nullable=True),
        sa.Column("hack_ucf", sa.Boolean(), nullable=True),
        sa.Column("interrupt_ucf", sa.Boolean(), nullable=True),
        sa.Column("manip_traffic", sa.Boolean(), nullable=True),
        sa.Column("bypass_dhcp", sa.Boolean(), nullable=True),
        sa.Column("pirate", sa.Boolean(), nullable=True),
        sa.Column("host_at_ucf", sa.Boolean(), nullable=True),
        sa.Column("cloud_aup", sa.Boolean(), nullable=True),
        sa.Column("signtime", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usermodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ethicsformmodel")
    op.drop_table("discordmodel")
    op.drop_table("usermodel")
    # ### end Alembic commands ###
