"""Add UCF student

Revision ID: 4875f19211ae
Revises: 2b1a94ac1009
Create Date: 2024-08-19 15:51:06.850670

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4875f19211ae"
down_revision: Union[str, None] = "2b1a94ac1009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodel", sa.Column("ucf_student", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "ucf_student")
    # ### end Alembic commands ###
