"""Update SQLmodel

Revision ID: ca6b82199288
Revises: b4cd696ddc31
Create Date: 2024-07-23 11:35:55.679843

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca6b82199288"
down_revision: Union[str, None] = "b4cd696ddc31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("discordmodel", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("discordmodel", "mfa", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "discordmodel", "avatar", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "discordmodel", "banner", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("discordmodel", "color", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("discordmodel", "nitro", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "discordmodel", "locale", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("usermodel", "mentor_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usermodel", sa.Column("mentor_name", sa.VARCHAR(), nullable=True))
    op.alter_column("discordmodel", "locale", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("discordmodel", "nitro", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("discordmodel", "color", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("discordmodel", "banner", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("discordmodel", "avatar", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("discordmodel", "mfa", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("discordmodel", "email", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
